### ISSUE TITLE
Crash when unit loses combat

### ISSUE THREAD

**Issue by rcriii42** [rcriii42/Pyre#16]
```
resolve_combat: 3rd Marines defeated by Boston
None <GroundUnits.Infantry object at 0x7fbc9d64e908>
Traceback (most recent call last):
  File "src/main.py", line 28, in <module>
    GW.mainloop(W)
  File "/home/rcriii/workspace/mPyre/src/GameWindow.py", line 261, in mainloop
    self.update(controller.G)
  File "/home/rcriii/workspace/mPyre/src/GameWindow.py", line 214, in update
    self.screen.render()
  File "/home/rcriii/workspace/mPyre/src/clickndrag/__init__.py", line 659, in render
    if Plane.render(self) or force or self.dragged_plane is not None:
  File "/home/rcriii/workspace/mPyre/src/clickndrag/__init__.py", line 312, in render
    if plane.render():
  File "/home/rcriii/workspace/mPyre/src/clickndrag/__init__.py", line 338, in render
    self.subplanes[name].rect)
TypeError: argument 1 must be pygame.Surface, not None
```

**Comment by rcriii42** [comment]
Somehow the unit.plane is being renamed along the way

```
game screen removed Unit 1st Infantry result['Unit 2nd Grenadiers', 'City of Jacksonville', 'City of Boston', 'City of New York', '1st Infantry']
selected 1st Infantry
1st Infantry moving 1, moved 0
check_collision: collided with New York
resolve_combat: 1st Infantry defeated by New York
Destroying Unit 1st Infantry
game screen removed Unit 1st Infantry result['Unit 2nd Grenadiers', 'City of Jacksonville', 'City of Boston', 'City of New York', '1st Infantry']
Unit 1st Infantry removed outlined_selection result[]
Unit 1st Infantry removed outlined_selection result[]
Destroying 1st Infantry
game screen removed 1st Infantry result['Unit 1st Infantry', 'Unit 2nd Grenadiers', 'City of Jacksonville', 'City of Boston', 'City of New York']
```
